### PR TITLE
Custom Thresholds

### PR DESCRIPTION
**Pull request by f-hkobin**
# Custom Thresholds
Addresses #50 and #49 

- Added a `Threshold` class that is constrained to the shape mentioned in #50 
- Modified `pyreason/scripts/utils/rule_parser.py` to handle custom thresholds (or use the default threshold if not defined)
- Added new test case and documentation for custom thresholding
- Added exception handling around specifying a custom threshold

We also worked on a numba type for the threshold, but I don't think it's needed in this current iteration, so we removed it. 

Please let us know if modifications are needed and we will be happy to help, myself or Kamini will jump in to make changes :thumbsup:

### CODE REVIEW

**Comment by dyumanaditya** [comment]
@f-hkobin Thanks for this, I will review and merge or get back to you if any changes are necessary soon.

**Comment by KaminiAggarwal** [comment]
@dyumanaditya Thanks for working upon the PR. Seems like the pipeline failed as shown in above details. 
Do we have an approx timeline on when it can be merged?

**Comment by dyumanaditya** [comment]
I will try and merge it this weekend or before. The check failing is weird since I'm not able to reproduce it locally

**Review by dyumanaditya — APPROVED** [review]

**Comment by dyumanaditya** [comment]
@f-hkobin @KaminiAggarwal Fixed the issue and merging, this will be in the next release `v2.3.0`

**Comment by KaminiAggarwal** [comment]
Thank you @dyumanaditya !

**Pull request merged**
